# Generated by Django 3.0.4 on 2020-05-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrocinador', '0001_initial'),
        ('aliado', '0002_auto_20200513_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.CharField(max_length=100)),
                ('aliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliado.Aliado')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrocinador.Patrocinador')),
            ],
            options={
                'verbose_name_plural': 'Misiones',
            },
        ),
    ]
