# Generated by Django 3.0.6 on 2020-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliado',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
