# Generated by Django 3.0.6 on 2020-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dinero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
    ]
